---
language: ruby
rvm: 2.0.0
env:
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.1
  - PUPPET_VERSION=3.7.2
  - PUPPET_VERSION=3.7.5
  - PUPPET_VERSION=4.1.0
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/920640c47e028fbb280b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
